-- Seed data for the internal clinic management system for CV Cipta Mandiri
-- This file contains seed data for patients, appointments, revenue, and audit log tables
-- Note: clinic_id has been removed as this is now an internal shared data system

-- Insert sample patients (at least 20 records)
INSERT INTO public.patients (id, first_name, last_name, email, phone, date_of_birth, gender, address, medical_history, created_at, updated_at) VALUES
  (gen_random_uuid(), 'Budi', 'Santoso', 'budi.santoso@example.com', '+6281212345678', '1985-03-15', 'Male', 'Jl. Merdeka No. 123, Jakarta', 'Hypertension, Diabetes', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
  (gen_random_uuid(), 'Siti', 'Aminah', 'siti.aminah@example.com', '+6281312345678', '1990-07-22', 'Female', 'Jl. Sudirman No. 45, Bandung', 'Asthma', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
  (gen_random_uuid(), 'Ahmad', 'Fauzi', 'ahmad.fauzi@example.com', '+6281232345678', '1978-11-08', 'Male', 'Jl. Gatot Subroto No. 67, Surabaya', 'None', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), 'Dewi', 'Kusuma', 'dewi.kusuma@example.com', '+6281112345678', '1987-01-30', 'Female', 'Jl. Hayam Wuruk No. 89, Yogyakarta', 'Allergy to Penicillin', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), 'Rizki', 'Pratama', 'rizki.pratama@example.com', '+6282112345678', '1992-09-14', 'Male', 'Jl. Diponegoro No. 101, Medan', 'Heart Condition', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), 'Lina', 'Wijaya', 'lina.wijaya@example.com', '+6282212345678', '1983-12-05', 'Female', 'Jl. Thamrin No. 23, Semarang', 'Diabetes', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
  (gen_random_uuid(), 'Firman', 'Hakim', 'firman.hakim@example.com', '+6281332345678', '1989-04-18', 'Male', 'Jl. Asia Afrika No. 56, Makassar', 'None', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
  (gen_random_uuid(), 'Maya', 'Sari', 'maya.sari@example.com', '+6281412345678', '1995-08-25', 'Female', 'Jl. Pemuda No. 78, Palembang', 'Asthma', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
  (gen_random_uuid(), 'Agus', 'Salim', 'agus.salim@example.com', '+6281512345678', '1981-02-10', 'Male', 'Jl. Veteran No. 90, Denpasar', 'Hypertension', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
  (gen_random_uuid(), 'Ratna', 'Permata', 'ratna.permata@example.com', '+6281612345678', '1993-06-12', 'Female', 'Jl. Imam Bonjol No. 34, Bandar Lampung', 'None', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
  (gen_random_uuid(), 'Hendra', 'Kurniawan', 'hendra.kurniawan@example.com', '+6281712345678', '1986-10-28', 'Male', 'Jl. Jend. Sudirman No. 12, Pontianak', 'Diabetes', NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
  (gen_random_uuid(), 'Yuni', 'Astuti', 'yuni.astuti@example.com', '+6281812345678', '1991-05-03', 'Female', 'Jl. Ahmad Yani No. 56, Banjarmasin', 'Allergy to Penicillin', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
  (gen_random_uuid(), 'Taufik', 'Hidayat', 'taufik.hidayat@example.com', '+6281912345678', '1984-11-19', 'Male', 'Jl. Raya Kuta No. 78, Mataram', 'None', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
  (gen_random_uuid(), 'Eka', 'Lestari', 'eka.lestari@example.com', '+6282012345678', '1988-03-07', 'Female', 'Jl. Raya Legian No. 90, Kupang', 'Asthma', NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
  (gen_random_uuid(), 'Indra', 'Lesmana', 'indra.lesmana@example.com', '+6282112345678', '1980-09-15', 'Male', 'Jl. Raya Sanur No. 23, Jayapura', 'Heart Condition', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
  (gen_random_uuid(), 'Siska', 'Putri', 'siska.putri@example.com', '+6282212345678', '1994-12-30', 'Female', 'Jl. Raya Padang Bai No. 45, Ambon', 'None', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
  (gen_random_uuid(), 'Rahmat', 'Sulaiman', 'rahmat.sulaiman@example.com', '+6282312345678', '1982-01-20', 'Male', 'Jl. Raya Uluwatu No. 67, Ternate', 'Hypertension', NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
  (gen_random_uuid(), 'Nurul', 'Hidayah', 'nurul.hidayah@example.com', '+6282412345678', '1996-07-09', 'Female', 'Jl. Raya Kintamani No. 89, Manado', 'Diabetes', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
  (gen_random_uuid(), 'Dian', 'Permadi', 'dian.permadi@example.com', '+6282512345678', '1987-04-25', 'Female', 'Jl. Raya Jatiluwih No. 101, Gorontalo', 'Allergy to Penicillin', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
  (gen_random_uuid(), 'Joko', 'Widodo', 'joko.widodo@example.com', '+6282612345678', '1985-11-13', 'Male', 'Jl. Raya Munduk No. 123, Palu', 'None', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
  (gen_random_uuid(), 'Ani', 'Sulistyo', 'ani.sulistyo@example.com', '+6282712345678', '1990-08-30', 'Female', 'Jl. Raya Puncak No. 145, Bengkulu', 'Asthma', NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
  (gen_random_uuid(), 'Agung', 'Prasetya', 'agung.prasetya@example.com', '+6282812345678', '1983-05-17', 'Male', 'Jl. Raya Bromo No. 167, Pangkal Pinang', 'Heart Condition', NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days');

-- Insert sample appointments (at least 20 records)
INSERT INTO public.appointments (id, patient_id, appointment_date, duration_minutes, status, notes, cost, created_at, updated_at, treatment_type, frequency, end_date) VALUES
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Budi' LIMIT 1), NOW() + INTERVAL '1 day', 30, 'scheduled', 'Initial consultation', 150000.00, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Siti' LIMIT 1), NOW() + INTERVAL '2 days', 45, 'scheduled', 'Follow-up appointment', 200000.00, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Ahmad' LIMIT 1), NOW() - INTERVAL '1 day', 60, 'completed', 'Regular check-up', 180000.00, NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Dewi' LIMIT 1), NOW() + INTERVAL '3 days', 30, 'scheduled', 'Vaccination appointment', 120000.00, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Rizki' LIMIT 1), NOW() - INTERVAL '3 days', 45, 'completed', 'Physical examination', 220000.00, NOW() - INTERVAL '5 days', NOW() - INTERVAL '3 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Lina' LIMIT 1), NOW() - INTERVAL '2 days', 30, 'completed', 'Dental check-up', 160000.00, NOW() - INTERVAL '6 days', NOW() - INTERVAL '2 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Firman' LIMIT 1), NOW() + INTERVAL '4 days', 60, 'scheduled', 'Annual physical', 250000.00, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Maya' LIMIT 1), NOW() + INTERVAL '1 week', 30, 'scheduled', 'Pregnancy check-up', 175000.00, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', 'ongoing', 'weekly', NOW() + INTERVAL '6 weeks'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Agus' LIMIT 1), NOW() - INTERVAL '4 days', 40, 'completed', 'Blood pressure monitoring', 140000.00, NOW() - INTERVAL '9 days', NOW() - INTERVAL '4 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Ratna' LIMIT 1), NOW() + INTERVAL '5 days', 45, 'scheduled', 'Eye examination', 190000.00, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Hendra' LIMIT 1), NOW() - INTERVAL '5 days', 50, 'completed', 'Diabetes management', 210000.00, NOW() - INTERVAL '11 days', NOW() - INTERVAL '5 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Yuni' LIMIT 1), NOW() + INTERVAL '6 days', 35, 'scheduled', 'Asthma check-up', 165000.00, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', 'ongoing', 'monthly', NOW() + INTERVAL '6 months'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Taufik' LIMIT 1), NOW() - INTERVAL '6 days', 55, 'completed', 'Heart examination', 240000.00, NOW() - INTERVAL '13 days', NOW() - INTERVAL '6 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Eka' LIMIT 1), NOW() + INTERVAL '7 days', 40, 'scheduled', 'Allergy test', 170000.00, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Indra' LIMIT 1), NOW() - INTERVAL '7 days', 50, 'completed', 'Cardiology follow-up', 230000.00, NOW() - INTERVAL '15 days', NOW() - INTERVAL '7 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Siska' LIMIT 1), NOW() + INTERVAL '8 days', 30, 'scheduled', 'General consultation', 145000.00, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Rahmat' LIMIT 1), NOW() - INTERVAL '8 days', 45, 'completed', 'Hypertension management', 185000.00, NOW() - INTERVAL '17 days', NOW() - INTERVAL '8 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Nurul' LIMIT 1), NOW() + INTERVAL '9 days', 60, 'scheduled', 'Diabetes education', 200000.00, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', 'ongoing', 'weekly', NOW() + INTERVAL '3 months'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Dian' LIMIT 1), NOW() - INTERVAL '9 days', 35, 'completed', 'Allergy follow-up', 155000.00, NOW() - INTERVAL '19 days', NOW() - INTERVAL '9 days', 'one-time', NULL, NULL),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Joko' LIMIT 1), NOW() + INTERVAL '10 days', 40, 'scheduled', 'Routine check-up', 160000.00, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', 'ongoing', 'yearly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Ani' LIMIT 1), NOW() - INTERVAL '10 days', 45, 'completed', 'Asthma management', 195000.00, NOW() - INTERVAL '21 days', NOW() - INTERVAL '10 days', 'ongoing', 'monthly', NOW() + INTERVAL '6 months'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Agung' LIMIT 1), NOW() + INTERVAL '11 days', 50, 'scheduled', 'Heart health check', 225000.00, NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days', 'one-time', NULL, NULL);

-- Insert sample revenue records (at least 20 records)
INSERT INTO public.revenue (id, appointment_id, amount, payment_method, status, transaction_date, notes, created_at) VALUES
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Initial consultation%' LIMIT 1), 150000.00, 'Cash', 'completed', NOW() - INTERVAL '5 days', 'Payment for initial consultation', NOW() - INTERVAL '5 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Follow-up appointment%' LIMIT 1), 200000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '4 days', 'Payment via bank transfer', NOW() - INTERVAL '4 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Regular check-up%' LIMIT 1), 180000.00, 'Credit Card', 'completed', NOW() - INTERVAL '3 days', 'Credit card payment', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Vaccination appointment%' LIMIT 1), 120000.00, 'Cash', 'completed', NOW() - INTERVAL '2 days', 'Cash payment for vaccination', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Physical examination%' LIMIT 1), 220000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '1 day', 'Payment for physical examination', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Dental check-up%' LIMIT 1), 160000.00, 'Cash', 'completed', NOW() - INTERVAL '6 days', 'Cash payment for dental check-up', NOW() - INTERVAL '6 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Annual physical%' LIMIT 1), 250000.00, 'Credit Card', 'completed', NOW() - INTERVAL '7 days', 'Credit card for annual checkup', NOW() - INTERVAL '7 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Pregnancy check-up%' LIMIT 1), 175000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '8 days', 'Payment for pregnancy check-up', NOW() - INTERVAL '8 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Blood pressure monitoring%' LIMIT 1), 140000.00, 'Cash', 'completed', NOW() - INTERVAL '9 days', 'Cash for BP monitoring', NOW() - INTERVAL '9 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Eye examination%' LIMIT 1), 190000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '10 days', 'Payment for eye exam', NOW() - INTERVAL '10 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Diabetes management%' LIMIT 1), 210000.00, 'Credit Card', 'completed', NOW() - INTERVAL '11 days', 'Credit card for diabetes management', NOW() - INTERVAL '11 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Asthma check-up%' LIMIT 1), 165000.00, 'Cash', 'completed', NOW() - INTERVAL '12 days', 'Cash payment for asthmas check', NOW() - INTERVAL '12 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Heart examination%' LIMIT 1), 240000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '13 days', 'Payment for heart examination', NOW() - INTERVAL '13 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Allergy test%' LIMIT 1), 170000.00, 'Cash', 'completed', NOW() - INTERVAL '14 days', 'Cash for allergy test', NOW() - INTERVAL '14 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Cardiology follow-up%' LIMIT 1), 230000.00, 'Credit Card', 'completed', NOW() - INTERVAL '15 days', 'Credit card for cardiology', NOW() - INTERVAL '15 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%General consultation%' LIMIT 1), 145000.00, 'Cash', 'completed', NOW() - INTERVAL '16 days', 'Cash for general consultation', NOW() - INTERVAL '16 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Hypertension management%' LIMIT 1), 185000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '17 days', 'Payment for hypertension management', NOW() - INTERVAL '17 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Diabetes education%' LIMIT 1), 200000.00, 'Credit Card', 'completed', NOW() - INTERVAL '18 days', 'Credit card for diabetes education', NOW() - INTERVAL '18 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Allergy follow-up%' LIMIT 1), 155000.00, 'Cash', 'completed', NOW() - INTERVAL '19 days', 'Cash payment for allergy follow-up', NOW() - INTERVAL '19 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Routine check-up%' LIMIT 1), 160000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '20 days', 'Payment for routine check-up', NOW() - INTERVAL '20 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Asthma management%' LIMIT 1), 195000.00, 'Credit Card', 'completed', NOW() - INTERVAL '21 days', 'Credit card for asthmas management', NOW() - INTERVAL '21 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Heart health check%' LIMIT 1), 225000.00, 'Cash', 'completed', NOW() - INTERVAL '22 days', 'Cash for heart health check', NOW() - INTERVAL '22 days');


-- Additional appointments for patients that need more ongoing treatment data
INSERT INTO public.appointments (id, patient_id, appointment_date, duration_minutes, status, notes, cost, created_at, updated_at, treatment_type, frequency, end_date) VALUES
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Maya' LIMIT 1), NOW() + INTERVAL '2 weeks', 30, 'scheduled', 'Weekly pregnancy check-up #2', 175000.00, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', 'ongoing', 'weekly', NOW() + INTERVAL '6 weeks'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Hendra' LIMIT 1), NOW() + INTERVAL '1 month', 30, 'scheduled', 'Monthly diabetes check-up #2', 210000.00, NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Yuni' LIMIT 1), NOW() + INTERVAL '1 month', 30, 'scheduled', 'Monthly asthmas check-up #2', 165000.00, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', 'ongoing', 'monthly', NOW() + INTERVAL '6 months'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Indra' LIMIT 1), NOW() + INTERVAL '1 month', 30, 'scheduled', 'Monthly cardiology follow-up #2', 230000.00, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year'),
  (gen_random_uuid(), (SELECT id FROM public.patients WHERE first_name = 'Rahmat' LIMIT 1), NOW() + INTERVAL '1 month', 30, 'scheduled', 'Monthly hypertension management #2', 185000.00, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days', 'ongoing', 'monthly', NOW() + INTERVAL '1 year');

-- Additional revenue records for the ongoing appointments
INSERT INTO public.revenue (id, appointment_id, amount, payment_method, status, transaction_date, notes, created_at) VALUES
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Weekly pregnancy check-up #2%' LIMIT 1), 175000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '8 days', 'Payment for weekly pregnancy check-up #2', NOW() - INTERVAL '8 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Monthly diabetes check-up #2%' LIMIT 1), 210000.00, 'Credit Card', 'completed', NOW() - INTERVAL '11 days', 'Payment for monthly diabetes check-up #2', NOW() - INTERVAL '11 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Monthly asthmas check-up #2%' LIMIT 1), 165000.00, 'Cash', 'completed', NOW() - INTERVAL '12 days', 'Cash for monthly asthmas check-up #2', NOW() - INTERVAL '12 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Monthly cardiology follow-up #2%' LIMIT 1), 230000.00, 'Bank Transfer', 'completed', NOW() - INTERVAL '15 days', 'Payment for monthly cardiology follow-up #2', NOW() - INTERVAL '15 days'),
  (gen_random_uuid(), (SELECT id FROM public.appointments WHERE notes LIKE '%Monthly hypertension management #2%' LIMIT 1), 185000.00, 'Cash', 'completed', NOW() - INTERVAL '17 days', 'Cash for monthly hypertension management #2', NOW() - INTERVAL '17 days');